### ISSUE TITLE
Blender exporter fails when lights or cameras are included

### ISSUE THREAD

**Issue by bensyverson** [mrdoob/three.js#10358]
##### Description of the problem 
Trying to export a JSON from macOS Blender (2.78) fails when Lights or Cameras are selected in the export settings. The output progresses normally until it hits a camera or light, and then it complains because it can't find a constant for `AREA_LIGHT`.

I'll take a look at `object.py`, but maybe this rings a bell for someone.

```INFO:THREE:Parsing object Camera
2016-12-14 18:09:13,749 - Three.Export - ERROR: Traceback (most recent call last):
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/__init__.py", line 51, in export_scene
    scene_.parse()
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/scene.py", line 108, in parse
    self._parse_objects()
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/scene.py", line 230, in _parse_objects
    obj = object_.Object(node, parent=self[constants.OBJECT])
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/object.py", line 12, in __init__
    self._node_setup()
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/object.py", line 89, in _node_setup
    self[constants.TYPE] = api.object.node_type(self.node)
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/api/object.py", line 55, in inner
    return func(obj, *args, **kwargs)
  File "/Users/bensyverson/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/api/object.py", line 317, in node_type
    AREA: constants.AREA_LIGHT,
AttributeError: module 'io_three.constants' has no attribute 'AREA_LIGHT'
```

##### Three.js version

- [ ] Dev
- [x] r82
- [ ] ...

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS
- [x] Mac

**Comment by mrdoob** [comment]
Have you tried with the last version in `dev`?

**Comment by bensyverson** [comment]
Just tried, and it seems to be working fine in `dev`!
