### ISSUE TITLE
Blender Exporter Crashes trying to export scene

### ISSUE THREAD

**Issue by kevzettler** [mrdoob/three.js#10629]
##### Description of the problem 
Blender Exporter Fails to produce a .json file and throws an error that could be improved with clarity

```python
Traceback (most recent call last):
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/__init__.py", line 812, in execute
    exporter.export_scene(filepath, settings)
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/__init__.py", line 51, in export_scene
    scene_.parse()
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/scene.py", line 102, in parse
    self._parse_textures()
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/scene.py", line 243, in _parse_textures
    tex_inst = texture.Texture(texture_name, self)
  File "/Users/kev/Library/Application Support/Blender/2.78/scripts/addons/io_three/exporter/texture.py", line 24, in __init__
    self[constants.WRAP] = (num[wrap[0]], num[wrap[1]])
KeyError: 'repeat'

location: <unknown location>:-1

location: <unknown location>:-1
```

Is there any way to get better logging from this?

**Comment by mrdoob** [comment]
Do you mind sharing the `.blend`?

**Comment by kevzettler** [comment]
@mrdoob you can download the blend here: http://kevzettler.com/robotbones/assets/models/mechsniper/blender/qubicle/rig-bones-mirrored.blend

**Comment by kevzettler** [comment]
Seems to be an issue with textures. If I don't export textures it completes successfully. 

stemming form this line : https://github.com/mrdoob/three.js/blob/dev/utils/exporters/blender/addons/io_three/exporter/texture.py#L24

**Comment by mrdoob** [comment]
I think 96f9ed2d058642ee88bdc32c8d9473203ef8e8df fixed that. Do you mind trying the latest?

https://github.com/mrdoob/three.js/tree/dev/utils/exporters/blender

**Comment by Mugen87** [comment]
I think we can close this issue, see https://github.com/mrdoob/three.js/issues/10928#issuecomment-286774322

**Comment by developer-lindner** [comment]
Got the same issue with latest version from dev branch:

![bildschirmfoto 2017-10-09 um 20 57 50](https://user-images.githubusercontent.com/5435866/31353903-a523865e-ad34-11e7-9a65-fc1993b91c3b.png)

Mac OS X, Blender 2.79

**Comment by cg-cnu** [comment]
Hey guys! Not sure if https://github.com/mrdoob/three.js/pull/12261 break anything!
I will investigate and get back soon 🙂
