### ISSUE TITLE
Tests that should be passing are marked TODO

### ISSUE THREAD

**Issue by donmccurdy** [mrdoob/three.js#12714]
Opening the tests now, I see:

> 1789 tests completed in 6063 milliseconds, with 590 failed, 0 skipped, and 1196 todo.
7647 assertions of 8916 passed, 1269 failed.

A lot of those "failures" are weird errors like this:

```
Source: at Object.QUnit.module.todo (http://localhost:8080/test/unit/three.source.unit.js:2788:9) at processModule (http://localhost:8080/node_modules/qunitjs/qunit/qunit.js:2733:16) at Function.module$1.todo (http://localhost:8080/node_modules/qunitjs/qunit/qunit.js:2797:4) at Object.QUnit.module (http://localhost:8080/test/unit/three.source.unit.js:2760:15) at processModule (http://localhost:8080/node_modules/qunitjs/qunit/qunit.js:2733:16) at Object.module$1 [as module] (http://localhost:8080/node_modules/qunitjs/qunit/qunit.js:2754:4) at http://localhost:8080/test/unit/three.source.unit.js:7:8
```

I only checked a few but I think those are happening because they are "passing" tests in a module that is marked as TODO. PropertyBinding.test.js and BufferGeometry.test.js are good examples of this. So in some previous change, a bunch of TODO test modules were added, and passing tests were accidentally included?

I'm also wondering about all the TODOs... we probably don't want unit tests on private methods, so maybe TODOs like `AnimationAction._updateTimeScale` can be removed.

@Itee thanks for the refactoring and ES6 modules stuff! Any ideas on this?

**Comment by donmccurdy** [comment]
I guess that individual tests should be marked as `QUnit.todo`, rather than entire modules?
