### ISSUE TITLE
Error: Cannot find module 'three/examples/js/loaders/ctm/ctm.js'

### ISSUE THREAD

**Issue by lazycat92** [mrdoob/three.js#17061]
##### It doesn't find this this module in the folders or github code

when I run a vue project , I can't make it successful. 

> screens@1.0.0 dev /Users/wuqian/Desktop/work/aomygod/screens
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'three/examples/js/loaders/ctm/ctm.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at recursion (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/addMethod.js:34:23)
    at arr.forEach (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/addMethod.js:30:13)
    at Array.forEach (<anonymous>)
    at recursion (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/addMethod.js:27:9)
    at arr.forEach (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/addMethod.js:55:13)
    at Array.forEach (<anonymous>)
    at Object.addSpecial (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/addMethod.js:41:9)
    at Object.<anonymous> (/Users/wuqian/Desktop/work/aomygod/screens/node_modules/import-three-examples/src/loaders.js:117:18)

##### Three.js version

- [ ] Dev

##### OS
- [ ] macOS

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests. There are already some Vue related topics so maybe you find an answer there:

https://discourse.threejs.org/tags/vue
