### ISSUE TITLE
OrbitControls creates webpack error when building angular app-shell

### ISSUE THREAD

**Issue by Matthbo** [mrdoob/three.js#17913]
##### Description of the problem

I'm unsure if I should post this here or on the angular-cli repo

Webpack gives an error when building app-shell with angular
```
Unexpected token {
D:\Projects\School\project c\Front-end\node_modules\three\examples\jsm\controls\OrbitControls.js:10
import {
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.three/examples/jsm/controls/OrbitControls (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:6198:18)
    at __webpack_require__ (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:20:30)        at Module../src/app/building-navigation/building-viewer/building-viewer.component.ts (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:3065:99)
    at __webpack_require__ (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:20:30)        at Module../src/app/building-navigation/building-viewer/building-viewer.component.ngfactory.js (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:2999:84)
    at __webpack_require__ (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:20:30)        at Module../src/app/building-navigation/building-navigation.component.ngfactory.js (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:2784:110)
    at __webpack_require__ (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:20:30)        at Module../src/app/app.server.module.ngfactory.js (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:2482:118)
```

It seems like this is a problem between webpack & ThreeJS, but I can't change the webpack settings since I use the angular-cli to build the app-shell for my project.

I import ThreeJS & OrbitControls into my component like this:
```
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls'
```

##### Three.js version

- [ ] Dev
- [x] r110
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)
Not relevant

**Comment by mrdoob** [comment]
> I'm unsure if I should post this here or on the angular-cli repo

I think it'd be better to report it to angular-cli first.
