### ISSUE TITLE
npm make-screenshot not working

### ISSUE THREAD

**Issue by fe1ixz** [mrdoob/three.js#23502]
**Describe the bug**

I am trying to generate a screenshot for a new example I want to contribute, but running npm make-screenshot xxx is not working, it yields
```
npm run make-screenshot xxxxx

> three@0.137.5 make-screenshot
> node test/e2e/puppeteer.js --make "xxxxx"

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'puppeteer' imported from /Users/fe1ix/devfolder_01/three.js/test/e2e/puppeteer.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```
**To Reproduce**

1. npm install
2. npm make-screenshot <example name>
3. fail with error

**Expected behavior**

screenshot generated

**Platform:**

 - Device: [Desktop]
 - OS: [MacOS]
 - Three.js version: [dev, r137.5]

**Comment by Mugen87** [comment]
I've tested it right now on macOS and it works as expected.

Have you already executed `npm i` in the `test` directory?

**Comment by mrdoob** [comment]
> Have you already executed `npm i` in the `test` directory?

That seems to be the case 👍
