### ISSUE TITLE
Examples: OutlinePass stopped working with new three version

### ISSUE THREAD

**Issue by sandersdevelopments** [mrdoob/three.js#23884]
**Describe the bug**

We have upgraded to the latest threejs version which unfortunately (seem to) broke the OutlinePass from '../node_modules/three/examples/jsm/postprocessing/OutlinePass.js';

Uncaught (in promise) Error: unsupported bufferData src type -1,3,0,-1,-1,0,3,-1,0
    at bufferData (showcase.js:14:441950)
    at WebGLRenderingContext.L.e.<computed> [as bufferData] (showcase.js:14:444913)
    at showcase.js:2:500991
    at Object.update (showcase.js:2:501612)
    at Object.update (showcase.js:2:650946)
    at Object.update (showcase.js:2:655453)
    at Ne (showcase.js:2:753839)
    at WebGL1Renderer.Oa.render (showcase.js:2:758518)
    at FullScreenQuad.render (Pass.js:61:12)
    at OutlinePass.render (OutlinePass.js:408:16)
            
***Code***
We use it like this: 

```
 self.outlinePass = new OutlinePass(
                new three.Vector2(window.innerWidth, window.innerHeight),
                self.sceneNode.obj3D.parent,
                self.camera
            );
            self.outlinePass.edgeStrength = 4;
            self.outlinePass.edgeGlow = 1;
            self.outlinePass.edgeThickness = 4;
            self.outlinePass.pulsePeriod = 4;
            self.outlinePass.visibleEdgeColor.set(self.configuration.haloColor || 0xffffff);

            effectComposer.addPass(self.outlinePass);
```

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [r139]

**Comment by Mugen87** [comment]
The official live example works as expected though: https://threejs.org/examples/webgl_postprocessing_outline

Do you mind demonstrating the issue with a live example? It's probably best to modify `webgl_postprocessing_outline` so the issue pops up.

**Comment by sandersdevelopments** [comment]
I'll try, ty. The problem is, we are using Matterport3D as a 3rd party vendor which uses it's own threejs instance under the hood. Upgrading it without providing any changelog or other internal info. But I'll try to reproduce with your provided example

**Comment by Mugen87** [comment]
> The problem is, we are using Matterport3D as a 3rd party vendor which uses it's own threejs instance under the hood.

Please understand that we can't properly support such use cases since the third party library might use an outdated and/or custom version of `three.js`.

>  But I'll try to reproduce with your provided example

Great! However, this issue will be closed until you can reproduce the issue with the official example.
