### ISSUE TITLE
3DMLoader: THREE is not defined at Rhino3dmLoader._createMaterial 

### ISSUE THREAD

**Issue by jjsolly** [mrdoob/three.js#24073]
https://github.com/mrdoob/three.js/blob/14030014c00a5a0f0e2b052d9b6773a6c49055f2/examples/jsm/loaders/3DMLoader.js#L291-L292
```
ReferenceError: THREE is not defined 
  at Rhino3dmLoader._createMaterial (https://unpkg.com/three@0.139.2/examples/jsm/loaders/3DMLoader.js:291:39) 
  at Rhino3dmLoader._createGeometry (https://unpkg.com/three@0.139.2/examples/jsm/loaders/3DMLoader.js:348:27) 
  at https://unpkg.com/three@0.139.2/examples/jsm/loaders/3DMLoader.js:134:31
```

@fraguada I think this one is for you? Working on something here and found that this error cropped up. Everything was working fine with various models until using one with a Texture then got an "OnError is not a function" from line 98 of the loader. Dug into underlying error and found the above. Thanks as always for the work on this!

**Comment by jjsolly** [comment]
Thanks @Mugen87!
