### ISSUE TITLE
GLTFExporter throws RangeError

### ISSUE THREAD

**Issue by fengxinming** [mrdoob/three.js#25179]
### Description

This is part of error stacks

```txt
Uncaught (in promise) RangeError: Invalid array length
    at getMinMax (GLTFExporter.js:248:8)
    at GLTFWriter.processAccessor (GLTFExporter.js:1038:18)
    at GLTFWriter.processAnimation (GLTFExporter.js:1857:18)
    at GLTFWriter.processInput (GLTFExporter.js:2140:9)
    at GLTFWriter.write (GLTFExporter.js:453:8)
    at GLTFExporter.parse (GLTFExporter.js:113:10)
    at UIRow.<anonymous> (Menubar.File.js:252:12)
```

### Reproduction steps

1. git clone https://github.com/mrdoob/three.js.git
2. npm install
3. npm run dev
4. after editor server running then import `three.js/examples/models/gltf/Horse.glb` and `three.js/examples/models/gltf/Stork.glb` into the editor scene
5. click file menu to export a glb file
6. open chrome dev tool to see error stacks

### Code

none

### Live example

none

### Screenshots

![image](https://user-images.githubusercontent.com/6262382/209297045-96932748-fcbc-40ae-92c0-df57dab33ac4.png)

### Version

0.147.0

### Device

Desktop

### Browser

Chrome

### OS

MacOS

**Comment by Mugen87** [comment]
I can reproduce. The error appears with with [r122](https://raw.githack.com/mrdoob/three.js/r122/editor/index.html) for the first time. At that time, the editor starts to support animation export with `GLTFExporter` (#20454). So the bug probably already existed in the exporter but did not become apparent.

Interestingly, the error only occurs with two or more morphed assets. Non-animated assets work as expected as well as a the combination of a one morphed and one skinned mesh.

**Comment by dcm03** [comment]
The RangeError: Invalid array length error typically occurs when you are trying to create an array with a length that is either negative or larger than the maximum length allowed by JavaScript.

In the provided stack trace, it appears that this error is being thrown in the getMinMax function at line 248 in the GLTFExporter.js file. This function is being called from the process Accessor function at line 1038 in the same file. It's difficult to say without more context, but it's possible that this error is occurring because an invalid array length is being passed to the getMinMax function or because the getMinMax function is trying to set an array length that is outside of the allowed range.

To resolve this error, you'll need to identify the root cause of the invalid array length and fix it. This may involve modifying the code that is calling the getMinMax function or modifying the getMinMax function itself. It's also possible that there is an issue with the data that is being processed by the getMinMax function, in which case you may need to fix or sanitize the data before it is passed to the function.

**Comment by donmccurdy** [comment]
I expect that this issue (#25179) and #25198 have the same cause. three.js animations reference their targets by a unique name. Importing two assets into the Editor, then exporting, may cause the animation from one model to be in conflict with another. This is fine in normal usage (scope an AnimationMixer to each model) but would require renaming objects for export in the Editor.

GLTFExporter probably cannot fix this; given an AnimationClip list with non-unique names, it's too late to figure out which clip goes where. Maybe this is something we fix in the Editor by prefixing clip names, or by warning users to rename things, or ... ?

**Comment by donmccurdy** [comment]
I expect that this issue (#25179) and #25198 have the same cause. three.js animations reference their targets by a unique name. Importing two assets into the Editor, then exporting, may cause the animation from one model to be in conflict with another. This is fine in normal usage (scope an AnimationMixer to each model) but would require renaming objects for export in the Editor.

GLTFExporter probably cannot fix this; given an AnimationClip list with non-unique names, it's too late to figure out which clip goes where. Maybe this is something we fix in the Editor by prefixing clip names, or by warning users to rename things, or ... ?
