### ISSUE TITLE
I During use threejs in electron,  Error creating WebGL context.

### ISSUE THREAD

**Issue by liangfz-kit** [mrdoob/three.js#25576]
### Description

[2023-02-27 14:09:16.682] [error] THREE.WebGLRenderer: Error creating WebGL context.
[2023-02-27 14:09:16.694] [error] Error: Error creating WebGL context.
    at new ra (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7677010)
    at Object.BrainBrowser.SurfaceViewer.modules.rendering (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7995663)
    at file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7319241
    at Array.forEach (<anonymous>)
    at Object.start (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7319208)
    at t.componentDidMount (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:11910029)
    at hs (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6681517)
    at Dl (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6698306)
    at t.unstable_runWithPriority (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:7113402)
    at Yi (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6640529)
[2023-02-27 14:09:16.699] [error] Error: Error creating WebGL context.
    at new ra (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7677010)
    at Object.BrainBrowser.SurfaceViewer.modules.rendering (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7995663)
    at file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7319241
    at Array.forEach (<anonymous>)
    at Object.start (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:2:7319208)
    at t.componentDidMount (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:11910029)
    at hs (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6681517)
    at Dl (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6698306)
    at t.unstable_runWithPriority (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:7113402)
    at Yi (file:///tmp/.mount_app.ApqXFuFI/resources/app.asar/dist/app.js:11:6640529)

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Version

three.r121

### Device

Desktop

### Browser

Chrome

### OS

Linux

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for this issue.
