### ISSUE TITLE
PLYLoader : RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by ParanoidKevin** [mrdoob/three.js#26229]
### Description

RangeError when adding a mesh into scene

Console:
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at Object.read (PLYLoader.js:568:1)
    at binaryReadElement (PLYLoader.js:543:1)
    at parseBinary (PLYLoader.js:643:1)
    at PLYLoader.parse (PLYLoader.js:710:1)
    at Object.onLoad (PLYLoader.js:71:1)
    at three.module.js:41507:1

.ply file 
[gripper.zip](https://github.com/mrdoob/three.js/files/11710514/gripper.zip)

### Reproduction steps

1.
2.
3.

### Code

```
const PLYL = new PLYLoader();
PLYL.load(
  "path/to/gripper.ply",
  function (geometry) {
    this.scene.add(new THREE.Mesh(geometry));
  },
  function (xhr) {
    console.log((xhr.loaded / xhr.total) * 100 + "% loaded");
  },
  function (err) {
    console.error(err);
  }
);
```

### Live example

https://codesandbox.io/s/quizzical-kepler-jjxj4f?file=/src/index.js

### Version

152

### Device

Desktop

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
I can confirm the issue. The asset used to load correctly with `r148`. It starts failing with `r149`

https://rawcdn.githack.com/mrdoob/three.js/r148/editor/index.html

@aardgoose It seems this regression was introduced with the performance improvements added via https://github.com/mrdoob/three.js/pull/25210, https://github.com/mrdoob/three.js/pull/25248 and https://github.com/mrdoob/three.js/pull/25261. Maybe something in https://github.com/mrdoob/three.js/pull/25248 isn't right.

**Comment by aardgoose** [comment]
I'll take a look.

**Comment by aardgoose** [comment]
OK, the problem is the example file has \r\n line endings and javascript is removing the \n characters in the strings returned in the regexp at:

https://github.com/mrdoob/three.js/blob/c8075f51e0baceff0feb459d143fb3586089fd2d/examples/jsm/loaders/PLYLoader.js#L112

As a result the header length is being calculated as 311 bytes long when including the \n characters it is actually 325 bytes. Hence the binary data isn't read correctly.

The following snippet replacing the section following the above line of code fixes the test case, but will obviously break with normal files.

```
			if ( result !== null ) {

				const newlineCount = result[ 0 ].match( /\r/g ).length;

				headerText = result[ 1 ];
				headerLength = new Blob( [ result[ 0 ] ] ).size + newlineCount;

			}
```
