### ISSUE TITLE
import TIFFLoader error

### ISSUE THREAD

**Issue by wtlovzjj** [mrdoob/three.js#26523]
### Description

npm install three v0.155.0
import {TIFFLoader} from 'three/examples/jsm/loaders/TIFFLoader.js';
utif.module.js:7 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at utif.module.js:7:1
    at Module.<anonymous> (utif.module.js:3802:1)
    at ./node_modules/three/examples/jsm/libs/utif.module.js (utif.module.js:3803:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./node_modules/three/examples/jsm/loaders/TIFFLoader.js (TIFFLoader.js:1:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./src/three/utils.js (utils.js:1:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./src/three/viewer.js (utils.js:200:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./src/App.jsx (index.less:7:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./src/Local.jsx (App.less:82:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at ./src/index.jsx (useURLParams.jsx:74:1)
    at __webpack_require__ (bootstrap:894:1)
    at fn (bootstrap:150:1)
    at 1 (views.js:589:1)
    at __webpack_require__ (bootstrap:894:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:87

### Reproduction steps

1. install three
2. import TIFFLoader

### Code

```js
import {TIFFLoader} from 'three/examples/jsm/loaders/TIFFLoader.js';
new TIFFLoader();
```

### Live example

..

### Version

0.155.0

### Browser

Chrome

### OS

Windows

**Comment by Mugen87** [comment]
Um, looks like there is an issue in the external `utif.module.js` lib that breaks the Webpack build.

What version of Webpack are you using?

**Comment by Mugen87** [comment]
Can you please try to update your local version of `utif.module.js` with [this code](https://github.com/Mugen87/three.js/blob/0fb7b11b6b41298864b1c49ec6e26c494841fde7/examples/jsm/libs/utif.module.js)? Does the build work now?

**Comment by wtlovzjj** [comment]
> Can you please try to update your local version of `utif.module.js` with [this code](https://github.com/Mugen87/three.js/blob/0fb7b11b6b41298864b1c49ec6e26c494841fde7/examples/jsm/libs/utif.module.js)? Does the build work now?

After I update this file locally, it will be ready

**Comment by wtlovzjj** [comment]
> Um, looks like there is an issue in the external `utif.module.js` lib that breaks the Webpack build.
> 
> What version of Webpack are you using?

the verson is 4.44.2

**Comment by Mugen87** [comment]
Thanks for testing! I'll file a PR.

**Comment by wtlovzjj** [comment]
> Thanks for testing! I'll file a PR.

Thanks,  I have another question now. I will use TIFFLoader to load a tif file， but the data obtained was undefined.
`
loader.load(fileToLoad, function (object) {
      let geometry;
      if (object.isGeometry || object.isBufferGeometry) {
        geometry = object;
      } else if (object.isGroup) {
        // merge geometries
        console.log(object);
        geometry = BufferGeometryUtils.mergeGeometries(
          object.children.map(child =>
            child.geometry.clone().applyMatrix4(child.matrix))
        );

        // Add indices if not exist
        console.log(object.children[0].isPoints);
        if (geometry.index === null && !object.children[0].isPoints) {
          const nVerts = geometry.getAttribute('position').length / 3;
          const indices = Array.from(Array(nVerts), (v, k) => k);
          geometry.setIndex(indices);
        }
      } else {
        // expect object is THREE.Mesh
        geometry = object.geometry;
      }

      console.log(geometry); // undefined 
    })
`

**Comment by Mugen87** [comment]
Please ask for help at the [forum](https://discourse.threejs.org/). GitHub is only for bugs and feature requests.
