### ISSUE TITLE
WebGLRenderTarget Texture breaks glTF export

### ISSUE THREAD

**Issue by marwie** [mrdoob/three.js#28652]
### Description

WebGLRenderTarget textures assigned to objects in the scene cause the GLTFExporter to throw at image export resulting in the glTF export to not work at all

### Reproduction steps

1. Create a WebGLRenderTarget
2. Assign `renderTarget.texture` to some material used in the scene
3. Try export with GLTFExporter
4. Observe error

```js
Error: THREE.GLTFExporter: Invalid image type. Use HTMLImageElement, HTMLCanvasElement, ImageBitmap or OffscreenCanvas.
    at GLTFWriter.processImage (GLTFExporter.js:1323:12)
    at GLTFWriter.processTexture (GLTFExporter.js:1430:17)
    at GLTFWriter.processMaterial (GLTFExporter.js:1516:17)
    at GLTFWriter.processMesh (GLTFExporter.js:1929:26)
    at GLTFWriter.processNode (GLTFExporter.js:2284:27)
    at GLTFWriter.processScene (GLTFExporter.js:2360:28)
    at GLTFWriter.processInput (GLTFExporter.js:2416:10)
    at GLTFWriter.write (GLTFExporter.js:552:8)
    at GLTFExporter.parse (GLTFExporter.js:202:10)
    at exportGLTF (misc_exporter_gltf.html:43:18)
```

### Code

```js
setTimeout(()=>{
	const renderTexture = new THREE.WebGLRenderTarget(256, 256);
	// not necessary but let's render the scene once
	renderer.setRenderTarget( renderTexture );
	renderer.render( scene1, camera );
	renderer.setRenderTarget( null );
	// add the render texture to an object in the scene
	const cube = new THREE.Mesh( new THREE.BoxGeometry( 200, 200, 200 ), new THREE.MeshBasicMaterial( { color: 0xffffff, map: renderTexture.texture } ) );				
	scene1.add( cube );
}, 10)
```

### Live example

https://github.com/needle-tools/three.js/tree/webglrendertarget-breaks-gltfexport

### Version

r165

### Device

Desktop, Mobile, Headset

### Browser

Chrome, Safari

### OS

MacOS

**Comment by marwie** [comment]
If the GLTFExporter had access to the Renderer one possible way to get this to work was by checking `isRenderTargetTexture` and passing the WebGLRenderer to the GLTFExporter - then the texture could be readback to a DataTexture with `renderer.readRenderTargetPixels` - is there a better solution and would you consider merging a PR for this?

**Comment by Mugen87** [comment]
So far the policy was that the app is responsible to prepare the asset to a state such that it can be exported with one of the exporters. That means turning render targets into real textures or bake the current animation state before exporting.

Granted, it is more convenient if exporters take automatically care of this but I fear a significant  increase in complexity if want to cover all possible use cases. E.g. in your PR you assume the user render target is always `RGBAFormat` + `UnsignedByteType` which is not always true. There are many different render target setups that could be used by apps for generating textures. None of these are handled in your PR, right now . 

There is also the question how to handle them. What would you do if an asset uses a render target with `HalfFloatType`? Or maybe `UnsignedByteType` but with `RedFormat`? Do you ignore it or convert the data somehow to RGBA8 so it can be exported to glTF?

To me, it's actually if the app makes that decision _before_ the export is executed.

**Comment by Mugen87** [comment]
The render target issue aside, I wonder if it was a good idea to let `GLTFExporter` automatically decompress textures. The dependency to `TextureUtils` and thus `WebGLRenderer` is problematic in context of WebGPU.

I wonder if it's better (at least until `three.js` has more than one renderer) to have a separate component that prepares asset for the export meaning transforms render target textures to data textures and decompresses texture.

**Comment by Mugen87** [comment]
Closing. The sheer number of render target premutations (UnsignedByteType vs half/float, RGBAFormat vs RGBFormat/R/RG, integer targets, MRT attachments, plus colorSpace and tone-mapping decisions for HDR) make a robust implementation challenging. So it's best if the application implements the readback according to its needs.
