### ISSUE TITLE
New Blender Exporter fails when 'Colors' box is checked in export options

### ISSUE THREAD

**Issue by phfatmonkey** [mrdoob/three.js#6019]
Steps to reproduce:

1. Export one untextured cube in ThreeJS format. The default Blender scene is what I used.
2. Make sure 'Colors' box is checked in the export options on the left.
3. Export fails with following console log message:

>Error recorded to C:\Users\Ryan\AppData\Local\Temp\io_three.export.log
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\__init__.py", line 577, in execute
    exporter.export_scene(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\__init__.py", line 16, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\__init__.py", line 47, in export_scene
    scene_.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\scene.py", line 65, in parse
    self.__parse_geometries()
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\scene.py", line 151, in __parse_geometries
    geo.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\geometry.py", line 128, in parse
    self.__parse_geometry()
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\geometry.py", line 325, in __parse_geometry
    self.node)
  File "C:\Program Files\Blender Foundation\Blender\2.73\scripts\addons\io_three\exporter\base_classes.py", line 20, in __setitem__
    raise exceptions.ThreeValueError(msg)
io_three.exceptions.ThreeValueError: Value is an invalid data type: <class 'NoneType'>

>location: <unknown location>:-1

>location: <unknown location>:-1

**Comment by repsac** [comment]
Does the cube have vertex colours?

Related to https://github.com/mrdoob/three.js/issues/6008#issuecomment-72400233

**Comment by phfatmonkey** [comment]
I would think not. It's the default scene with one cube so I'm guessing there aren't any vertex colors on there. Is that what the 'Colors' box refers to? I was thinking it was the material colors: diffuse, ambient, spec, etc.

**Comment by repsac** [comment]
> Is that what the 'Colors' box refers to? 

yes, it's a carry over from the old exporter that I will probably change. As a quick note:
- `Materials` is for scene exports
- `Face Materials` are for geometry exports

I am probably going to have to look at how the options are grouped so that it is clearer what the context (scene or geometry) each should be used in

**Comment by repsac** [comment]
This was a quick fix and will be included in my next PR

**Comment by repsac** [comment]
Fixed https://github.com/mrdoob/three.js/pull/6048/
