### ISSUE TITLE
Blender Exporter r73: Exporting Skeletal Animations with Skinned Mesh outputs incorrect vert positions

### ISSUE THREAD

**Issue by phfatmonkey** [mrdoob/three.js#8337]
##### Description of the problem 

This is related to issue #8317. I've applied the fix suggested by @insominx in that issue.

In comparing exported data from r68 and r73, vertex positions are different between the two and result in model being flipped on it's side.

###### Steps to reproduce
To reproduce, load the attached file two_tris.blend and export using r68 and r73 exporters.

Settings in r73:

![image](https://cloud.githubusercontent.com/assets/3812933/13685090/a1506760-e6c3-11e5-9b28-737457454fa9.png)

- Under GEOMETRY, check Bones and Skinning
- Under Skeletal Animations, select Pose and check Keyframe Animations
- Under SCENE, check Scene and Hierarchies

Settings in r68

![image](https://cloud.githubusercontent.com/assets/3812933/13685158/f7691f34-e6c3-11e5-960f-037ba8a72586.png)

- Under Animation, Check Skeletal Animations

The vert positions in the two exported files are different. Also note that when Hierarchies is checked when exporting from r73, the matrix that's generated transform the verts after ingestion is the identity matrix, so it's net result should be nothing. 

Rendered result:
![image](https://cloud.githubusercontent.com/assets/3812933/13685359/f1ef8af6-e6c4-11e5-88ed-eccd817137b0.png)

##### Three.js version

- [x] Dev
- [ ] r74
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by phfatmonkey** [comment]
Forgot to upload the test Blender file
[two_tris.zip](https://github.com/mrdoob/three.js/files/168048/two_tris.zip)

**Comment by phfatmonkey** [comment]
###### More info
I swapped the Y and Z vert positions in mesh.py:

`vector = (vertex.co.x, vertex.co.z, -vertex.co.y)`

in lines 151, 406 and 759

 and then exported with hierarchies checked on and the result looks as it should:

![image](https://cloud.githubusercontent.com/assets/3812933/13685429/46544262-e6c5-11e5-87e8-490feebc779c.png)

I tried this with a few other blend files with success:

- Two pyramids (from issue #8317)
![image](https://cloud.githubusercontent.com/assets/3812933/13685491/9b46a954-e6c5-11e5-8a6c-3b5fbc3c31b3.png)

- Cylinder with 5 bones:
![image](https://cloud.githubusercontent.com/assets/3812933/13685588/f874bd8c-e6c5-11e5-8bc3-f205bf74fe40.png)

- the Marine with the IK rig:
![image](https://cloud.githubusercontent.com/assets/3812933/13685563/dbf7c60e-e6c5-11e5-81ca-4ef9277a1dd4.png)

However I did get this error when trying to re-export the marine_anims.blend file that comes packaged with the examples in r73:

`
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\__init__.py", line 787, in execute
    exporter.export_scene(filepath, settings)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\__init__.py", line 20, in inner
    func(filepath, options, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\__init__.py", line 51, in export_scene
    scene_.parse()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\scene.py", line 108, in parse
    self._parse_objects()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\scene.py", line 230, in _parse_objects
    obj = object_.Object(node, parent=self[constants.OBJECT])
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\object.py", line 12, in __init__
    self._node_setup()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\object.py", line 133, in _node_setup
    tracks = api.object.animated_xform(self.node, self.options)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\api\object.py", line 53, in inner
    return func(obj, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\addons\io_three\exporter\api\object.py", line 233, in animated_xform
    for time in times:
TypeError: 'NoneType' object is not iterable
`

I've tracked it down to the action 'Tpose.' I know there's an error with the action itself but I'm not sure what it is exactly. I removed it and created a new one from which to grab the bind pose and I 
[marine_anims with new action for grabbinbg bind pose.zip]
got it to export. However, this is the result. 

I had to zoom out a lot to see the bone visualization:
![image](https://cloud.githubusercontent.com/assets/3812933/13685835/76f4a4a0-e6c7-11e5-8441-6fc9726d12cd.png)

Then I noticed the marine was scaled up by a factor of 100 so I applied the transformation (baked the the scale) and re-exported and I got this:
![image](https://cloud.githubusercontent.com/assets/3812933/13685946/0a5126ba-e6c8-11e5-9a63-41f0cc513496.png)

It looks fine, but the model was really large now, so I had to zoom out quite a bit to see it.

Here's an updated marine_anims.blend file, the exported JSON and the mesh.py file with my changes.
(https://github.com/mrdoob/three.js/files/168066/marine_anims.with.new.action.for.grabbinbg.bind.pose.zip)

I'd like to make a pull request so I can look more into this issue. 


...

**Comment by MaikSoriano** [comment]
Three.js r77, this is happening right now and I have tried diferents parameters with the blender exporter. Idk what is wrong but I'm block with this issue:

https://www.youtube.com/watch?v=5ujqS3nm5RQ

**Comment by Mugen87** [comment]
The JSON Blender exporter has been removed with `R93` (#14117). 

Also see: https://threejs.org/docs/#manual/introduction/Loading-3D-models
