### ISSUE TITLE
[help] blender exporter, how to remove blender default cube when export scene?

### ISSUE THREAD

**Issue by hakur** [mrdoob/three.js#9932]
##### Description of the problem 
hello
 i have try this code ,but get crash
```python
import bpy
bpy.ops.outliner.object_operation(type="DELETE")
bpy.ops.export.three(
	filepath='a.json',
)
```
```
$ blender -b --python three.py
Read new prefs: C:\Users\xing.yu\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490
found bundled python: F:\ProgramFiles\blender-2.77\2.77\python
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "d:\t\three.py", line 2, in <module>
    bpy.ops.outliner.object_operation(type="DELETE")
  File "F:\ProgramFiles\blender-2.77\2.77\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.outliner.object_operation.poll() failed, context is incorrect

Blender quit
```
blender version 2.77
plugin version 1.5.0
##### Three.js version
- [x] r81
##### OS

- [x] Windows

**Comment by hakur** [comment]
all right.
i got resolved,
blender load
```
C:\Users\xing.yu\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend
```
as the default scene


so, i make a empty scene ,and press ctrl+u save it as default scene

but there is a problem,

i have to left an object and make it select=True, otherwise 
```
RuntimeError: Operator bpy.ops.outliner.object_operation.poll() failed, context is incorrect
```
will be print again

(my english is poor)
